### ISSUE TITLE
Can't Start oomox-gui

### ISSUE THREAD

**Issue by Dobbie03** [themix-project/oomox#150]
Running Oomox on ArchLabs/Arch.  When called from terminal with "oomox-gui" I get this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/oomox/oomox_gui/__init__.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by Dobbie03** [comment]
Fixed by re-installing "python-gobject"

Closing..
