### ISSUE TITLE
Spotify Theme

### ISSUE THREAD

**Issue by iiPlasma** [themix-project/oomox#155]
Everytime I try and run spotify it tells me I need to "Please choose the font options:" then it's just blank

**Comment by actionless** [comment]
screenshots please

**Comment by tom-davies** [comment]
I'm having the same problem:
![image](https://user-images.githubusercontent.com/170247/44045913-ed3ca094-9f21-11e8-927a-17b1a775fd63.png)

**Comment by iiPlasma** [comment]
Yep his picture is what I get. When I try and export to Spotify it gives me that blank box that says Please choose the font options:

**Comment by actionless** [comment]
try running `oomox-gui` via terminal and see if it will write anything

**Comment by tom-davies** [comment]
```
Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/presets_list.py", line 30, in on_preset_select
    current_theme, current_preset_path
  File "/opt/oomox/oomox_gui/main.py", line 248, in on_preset_selected
    self.load_colorscheme(read_colorscheme_from_path(selected_preset_path))
  File "/opt/oomox/oomox_gui/theme_file_parse.py", line 73, in read_colorscheme_from_path
    with open(preset_path) as file_object:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/oomox/oomox_gui/../colors/base16'
Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/main.py", line 321, in _on_export_plugin
    colorscheme=self.colorscheme
  File "/opt/oomox/oomox_gui/../plugins/oomoxify/oomox_plugin.py", line 115, in __init__
    self._init_radios()
  File "/opt/oomox/oomox_gui/../plugins/oomoxify/oomox_plugin.py", line 89, in _init_radios
    self.font_name_entry = Gtk.Entry(text=self.export_config[OPTION_FONT_NAME])
  File "/opt/oomox/oomox_gui/export_config.py", line 40, in __getitem__
    return self.config[item]
KeyError: 'font_name'
```

**Comment by actionless** [comment]
what oomox version do you run? it seems not up to date judging from line numbers

**Comment by actionless** [comment]
i've just noticed what stable AUR package have too old oomoxify plugin, i am not maintainer of that aur package but i have write access so i've updated it

**Comment by tom-davies** [comment]
That's great, thanks! Looks like it's sorted!

**Comment by actionless** [comment]
thanks for testing!
