### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by VoidNoire** [themix-project/oomox#159]
Running `oomox-gui` results in output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/share/oomox/oomox_gui/__main__.py", line 1, in <module>
    from .main import main
  File "/usr/share/oomox/oomox_gui/main.py", line 17, in <module>
    from .theme_file_parse import read_colorscheme_from_path
  File "/usr/share/oomox/oomox_gui/theme_file_parse.py", line 1, in <module>
    from .theme_model import THEME_MODEL
  File "/usr/share/oomox/oomox_gui/theme_model.py", line 4, in <module>
    from .plugin_loader import (
  File "/usr/share/oomox/oomox_gui/plugin_loader.py", line 58, in <module>
    init_plugins()
  File "/usr/share/oomox/oomox_gui/plugin_loader.py", line 41, in init_plugins
    os.path.join(plugin_path, "oomox_plugin.py")
  File "/usr/share/oomox/oomox_gui/plugin_loader.py", line 16, in get_plugin_module
    spec.loader.exec_module(module)
  File "/usr/share/oomox/oomox_gui/../plugins/import_pil/oomox_plugin.py", line 37, in <module>
    image_analyzer = load_python_module('ima', os.path.join(PLUGIN_DIR, 'ima.py'))  # pylint: disable=invalid-name
  File "/usr/share/oomox/oomox_gui/../plugins/import_pil/oomox_plugin.py", line 30, in load_python_module
    spec.loader.exec_module(module)
  File "/usr/share/oomox/plugins/import_pil/ima.py", line 1, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

Distro: Void Linux
Package: oomox 1.6.2_1 from void-packages

**Comment by actionless** [comment]
that's a packaging issue, please report that to void

**Comment by actionless** [comment]
or, the second, option, to disable the plugin which is using PIL:

https://github.com/themix-project/oomox/blob/master/Makefile#L8
