### ISSUE TITLE
plugin error  [SOLVED]

### ISSUE THREAD

**Issue by MusArco** [themix-project/oomox#262]
Hello Oomox developer,

I posted the question also at Arcolinux forum as i don't know if it is a Arch issue or Oomox.
In the link a screenshot of the error. All the plugin folders give an error.
I can't remember when or how this happened.

I am happy to give more details if needed.

[https://www.flickr.com/photos/145707276@N04/48715862187/in/datetaken-public/](url)

Thanks in advance 

system Arcolinux D I3 xfce-panel

**Comment by mxMu5** [comment]
output when openin in terminal :+1: 


 File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/oomox/oomox_gui/__main__.py", line 1, in <module>
    from .main import main
  File "/opt/oomox/oomox_gui/main.py", line 23, in <module>
    from .preset_list import ThemePresetList
  File "/opt/oomox/oomox_gui/preset_list.py", line 8, in <module>
    from .settings import UI_SETTINGS
  File "/opt/oomox/oomox_gui/settings.py", line 91, in <module>
    preset_list_sections_expanded={},
  File "/opt/oomox/oomox_gui/settings.py", line 80, in __init__
    default_config=default_config
  File "/opt/oomox/oomox_gui/settings.py", line 32, in __init__
    self.load()
  File "/opt/oomox/oomox_gui/settings.py", line 43, in load
    for key, value in json.load(file_object).items():
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mxMu5** [comment]
i also got an error with bleachbit

Traceback (most recent call last):
  File "/usr/share/bleachbit/GUI.py", line 250, in do_startup
    self.build_app_menu()
  File "/usr/share/bleachbit/GUI.py", line 98, in build_app_menu
    builder.add_from_file(bleachbit.app_menu_filename)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/share/data/app-menu.ui”: No such file or directory (4)
Traceback (most recent call last):
  File "/usr/share/bleachbit/GUI.py", line 284, in do_activate
    application=self, title=APP_NAME, auto_exit=self._auto_exit)
  File "/usr/share/bleachbit/GUI.py", line 466, in __init__
    self.populate_window()
  File "/usr/share/bleachbit/GUI.py", line 970, in populate_window
    self.headerbar = self.create_headerbar()
  File "/usr/share/bleachbit/GUI.py", line 913, in create_headerbar
    builder.add_from_file(bleachbit.app_menu_filename)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/share/data/app-menu.ui”: No such file or directory (4)


Python issue ?

**Comment by mxMu5** [comment]
At the moment i am looking at it with Erik Dubios from Arcolinux. I think this is a system issue and not a oomox issue.

**Comment by actionless** [comment]
please try with the latest `oomox-git`

**Comment by MusArco** [comment]
[SOLVED]

When i removed some packages related to python qt5 . 
I just did some guesses, what i thought could be a problem, to remove (some qt5 and python stuff).

Oomox is running again. 

I do not use the git version. and works fine.  I think it had something to do with my system config interfering.

Thanks for the reply.

**Comment by actionless** [comment]
that's weird, mb those packages were overriding `json` standard lib in some way

anyway with the fix i've added oomox app won't be stopping if it can't read the config for some reason

**Comment by actionless** [comment]
hm, i've re-read again,

> and restored config files and user dir. 

i think that actually solved the problem for you

**Comment by MusArco** [comment]
I think the same now, my configs.  ;)

Nice work !
