### ISSUE TITLE
Error when starting Oomox

### ISSUE THREAD

**Issue by jgpws** [themix-project/oomox#449]
I just re-installed the Themix full package on my system, but now when I launch the application with `oomox-gui` I get the following error:

```
Error loading plugin "icons_suruplus_aspromauros"
/opt/oomox/plugins/icons_suruplus_aspromauros:
cannot import name '_' from 'oomox_gui.i18n' (/opt/oomox/oomox_gui/i18n.py)

Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/plugin_loader.py", line 88, in init_plugins
    cls.load_plugin(plugin_name, plugin_path)
  File "/opt/oomox/oomox_gui/plugin_loader.py", line 57, in load_plugin
    plugin_module = get_plugin_module(
  File "/opt/oomox/oomox_gui/helpers.py", line 25, in get_plugin_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/oomox/plugins/icons_suruplus_aspromauros/oomox_plugin.py", line 8, in <module>
    from oomox_gui.i18n import _
ImportError: cannot import name '_' from 'oomox_gui.i18n' (/opt/oomox/oomox_gui/i18n.py)
```
The application pops-up a small window with nothing in it.

**Comment by actionless** [comment]
as a first line of the log suggests you have incompatible version of that plugin installed - make sure every of them are up-to-date
