### ISSUE TITLE
oomox-gui import error

### ISSUE THREAD

**Issue by dancer69** [themix-project/oomox#451]
I'm trying to run oomox-gui on archlinux and just open a small white window with only minimize button accessible and hangs there.
This is the error I get running from terminal:
`
Error loading plugin "icons_gnomecolors"
/opt/oomox/plugins/icons_gnomecolors:
cannot import name '_' from 'oomox_gui.i18n' (/opt/oomox/oomox_gui/i18n.py)

Traceback (most recent call last):
  File "/opt/oomox/oomox_gui/plugin_loader.py", line 88, in init_plugins
    cls.load_plugin(plugin_name, plugin_path)
  File "/opt/oomox/oomox_gui/plugin_loader.py", line 57, in load_plugin
    plugin_module = get_plugin_module(
  File "/opt/oomox/oomox_gui/helpers.py", line 25, in get_plugin_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/oomox/plugins/icons_gnomecolors/oomox_plugin.py", line 6, in <module>
    from oomox_gui.i18n import _
ImportError: cannot import name '_' from 'oomox_gui.i18n' (/opt/oomox/oomox_gui/i18n.py)
`

**Comment by actionless** [comment]
please make sure what you have the latest of versions of both gui and plugin

**Comment by actionless** [comment]
try removing all packages containing `themix` or `oomox` in the name in and install `themix-full-git` again
